# Generated by Django 5.0.6 on 2024-07-04 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diets', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDiet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diets.diet')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
